### ISSUE TITLE
Android + Azure Communication Services sample for Xamarin (C#)

### ISSUE THREAD

**Issue by mcblacksea** [Azure-Samples/communication-services-android-quickstarts#20]
Is it possible to provide sample for Azure Communication Services on Xamarin / Xamarin.Forms on C#?

> ---------------------------------------------------------------
> Thanks!

**Comment by JoshuaLai** [comment]
https://github.com/Azure-Samples/communication-services-ui-library-xamarin
We do have some samples in this repo on how we have created bindings for our calling sdk. Feel free to take a look if you haven't already.
